# Generated by Django 5.1 on 2024-08-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.SmallIntegerField(verbose_name='Employee ID')),
                ('report_id', models.SmallIntegerField(verbose_name='Report ID')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Hours Worked')),
                ('job_group', models.CharField(max_length=1, verbose_name='Job Group')),
                ('work_date', models.DateField(verbose_name='Work Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
        ),
    ]
